// packages/vue-translations/src/lib/components/translationProvider/TranslationProvider.vue
<script lang="ts" setup>
import { BaseTranslationsType, TranslationsType } from '@resourge/translations';
import { onMounted, onUnmounted, provide, reactive, readonly, toRefs } from 'vue'
import { SetupVueTranslationInstance } from '../../SetupVueTranslations.js';

export type TranslationProviderProps = {
    TranslationInstance: SetupVueTranslationInstance<string, TranslationsType<string> | BaseTranslationsType>
}

const props = defineProps<TranslationProviderProps>()

await props.TranslationInstance.promise;

const { instance } = toRefs(reactive({
    instance: props.TranslationInstance
}))

let missingRequestKeysRemove = () => {}

let languageChangeRemove = () => {}

onMounted(() => {
    missingRequestKeysRemove = props.TranslationInstance.addEventListener('missingRequestKeys', function () {
        instance.value = props.TranslationInstance
    })
    languageChangeRemove = props.TranslationInstance.addEventListener('languageChange', function () {
    	instance.value = props.TranslationInstance
    })
})

onUnmounted(() => {
    missingRequestKeysRemove()
    languageChangeRemove()
})

provide(props.TranslationInstance.TranslationsSymbol, readonly({ instance }));
</script>

<template>
	<slot />
</template>

// packages/react-translations/src/lib/components/translationProvider/TranslationProvider.tsx
import React, { type ReactNode, useEffect, useState } from 'react';

import { type BaseTranslationsType, type TranslationsType } from '@resourge/translations';

import { type SetupReactTranslationInstance } from '../../types/types';

export type TranslationProviderProps<
	Langs extends string, 
	Trans extends TranslationsType<Langs> | BaseTranslationsType
> = {
	children: ReactNode
	TranslationInstance: SetupReactTranslationInstance<
		Langs,
		Trans
	>
}

function TranslationProvider<
	Langs extends string, 
	Trans extends TranslationsType<Langs> | BaseTranslationsType
>({ TranslationInstance, children }: TranslationProviderProps<Langs, Trans>) {
	const _instance = TranslationInstance.wrapPromise.read();
			
	const [value, setValue] = useState({
		instance: _instance
	});

	useEffect(() => {
		const missingRequestKeysRemove = TranslationInstance.addEventListener('missingRequestKeys', function () {
			setValue({
				instance: TranslationInstance 
			});
		})

		const languageChangeRemove = TranslationInstance.addEventListener('languageChange', function () {
			setValue({
				instance: TranslationInstance
			});
		})

		return () => {
			missingRequestKeysRemove();
			languageChangeRemove();
		}
	}, [TranslationInstance])

	return (
		<TranslationInstance.Context.Provider value={value}>
			{ children }
		</TranslationInstance.Context.Provider>
	);
};

export default TranslationProvider;
